apiVersion: v1
kind: Service
metadata:
  name: {{ include "gangway.fullname" . }}
  labels:
    app: {{ include "gangway.name" . }}
    chart: {{ include "gangway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.config.port }}
      protocol: TCP
      name: gangway
  selector:
    app: {{ include "gangway.name" . }}
    release: {{ .Release.Name }}
