dependencies:
- name: docker-registry
  version: 1.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: mariadb
  version: 2.1.1
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mariadb.enabled
- name: minio
  version: 0.1.4
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: minio.enabled
